version: "3"
services:
  axmouth.dev-host-access:
    image: qoomon/docker-host
    cap_add: ["NET_ADMIN", "NET_RAW"]
    # mem_limit: 8M
    restart: unless-stopped
    container_name: axmouth.dev-host-access
  axmouth.dev-postfix:
    image: boky/postfix
    container_name: axmouth.dev-postfix
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS=true
      - ALLOWED_SENDER_DOMAINS
      - POSTFIX_myhostname=axmouth.dev-postfix
      #- POSTFIX_smtpd_recipient_restrictions=permit_sasl_authenticated, permit_mynetworks
      #- POSTFIX_smtpd_relay_restrictions=permit_mynetworks permit_sasl_authenticated defer_unauth_destination
      #- POSTFIX_mynetworks= 192.168.1.0/24 127.0.0.0/8
      #- RELAYHOST_TLS_LEVEL=secure
      #- POSTFIX_smtpd_use_tls=no
    ports:
      - 1587:587

  axmouth.dev-backend:
    working_dir: /var/lib/axmouth/axmouth.dev/backend
    restart: unless-stopped
    #network_mode: host
    tty: true
    image: ghcr.io/axmouth/axmouth.dev-backend:latest
    container_name: axmouth.dev-backend
    ports:
      - "39051:39051"
    env_file:
      - ./.env
    environment:
      - BIND_ADDRESS
      - CAPTCHA_SECRET
      - CAPTCHA_VERIFY_URL
      - CONTACT_ADDRESS
      - DATABASE_URL
      - JWT_SECRET
      - JWT_DURATION
      - MAIL_FROM_NAME
      - MAIL_FROM_ADDRESS
      - MAIL_HOST
      - MAIL_PASSWORD
      - MAIL_PORT
      - MAIL_USERNAME
      - RUST_LOG
      - STATIC_FILE_DIR
      - STATIC_FILE_ADDRESS
      - WEBSITE_URL
    volumes:
      - axmouth.dev-files:/var/lib/axmouth/axmouth.dev/static-assets:rw
volumes:
  axmouth.dev-files:
