FROM node:14

## Install http-server
# RUN npm install http-server -g
COPY --from=ghcr.io/axmouth/axmouth.dev-user-client-builder /app/dist /app/dist

# CMD ["nginx", "-g", "daemon off;"]

WORKDIR /app
RUN chmod +x /app/dist/ng-user-client/server/main.js

CMD ["node", "/app/dist/ng-user-client/server/main.js"]