version: "3"
services:
  axmouth.dev-backend:
    working_dir: /var/lib/axmouth/axmouth.dev/backend
    restart: unless-stopped
    network_mode: host
    tty: true
    image: ghcr.io/axmouth/axmouth.dev-backend:latest
    container_name: axmouth.dev-backend
    ports:
      - "39051:39051"
    env_file:
      - ./.env
    environment:
      - BIND_ADDRESS
      - CAPTCHA_SECRET
      - CAPTCHA_VERIFY_URL
      - CONTACT_ADDRESS
      - DATABASE_URL
      - JWT_SECRET
      - JWT_DURATION
      - MAIL_FROM_NAME
      - MAIL_FROM_ADDRESS
      - MAIL_HOST
      - MAIL_PASSWORD
      - MAIL_PORT
      - MAIL_USERNAME
      - RUST_LOG
      - STATIC_FILE_DIR
      - STATIC_FILE_ADDRESS
      - WEBSITE_URL
    volumes:
      - axmouth.dev-files:/var/lib/axmouth/axmouth.dev/static-assets:rw
volumes:
  axmouth.dev-files:
