//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "projects_technologies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub technology_id: i32,
    pub project_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::technologies::Entity",
        from = "Column::TechnologyId",
        to = "super::technologies::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Technologies,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::technologies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Technologies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
