//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
    pub description: Option<String>,
    pub cover_image: Option<String>,
    pub name: String,
    pub published: bool,
    pub slug: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::projects_technologies::Entity")]
    ProjectsTechnologies,
}

impl Related<super::projects_technologies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsTechnologies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
