name: Publish Docker image of axmouth.dev Backend to GHCR then update the image version on server

on: [push]

jobs:
  push_to_registry_and_deploy_to_server:
    if: github.ref == 'refs/heads/master'
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Github Container Registry with Docker
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull the previous version of Docker image for the build stage from Github Container Registry
        run: docker pull ghcr.io/axmouth/axmouth.dev-backend-builder || true
      - name: Pull the previous version of the final Docker image from Github Container Registry
        run: docker pull ghcr.io/axmouth/axmouth.dev-backend || true
      - name: Build the new version of the builder image
        run: docker build . --file Dockerfile.api.builder --tag ghcr.io/axmouth/axmouth.dev-backend-builder --cache-from=ghcr.io/axmouth/axmouth.dev-backend-builder
      - name: Build the new version of the final image
        run: docker build . --file Dockerfile.api.final --tag ghcr.io/axmouth/axmouth.dev-backend --cache-from=ghcr.io/axmouth/axmouth.dev-backend
      - name: Tag builder image
        run: docker tag ghcr.io/axmouth/axmouth.dev-backend-builder latest
      - name: Tag final image
        run: docker tag ghcr.io/axmouth/axmouth.dev-backend latest
      - name: Push builder image to GHCR
        run: docker push ghcr.io/axmouth/axmouth.dev-backend-builder || true
      - name: Push final image to GHCR
        run: docker push ghcr.io/axmouth/axmouth.dev-backend || true
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create empty .env file
        run: touch .env
      - name: Pull the previous version of Docker image for the build stage from Github Container Registry
        run: docker pull ghcr.io/axmouth/axmouth.dev-user-client-builder || true
      - name: Pull the previous version of the final Docker image from Github Container Registry
        run: docker pull ghcr.io/axmouth/axmouth.dev-user-client || true
      - name: Build the new version of the builder image
        run: docker build . --file Dockerfile.user.client.builder --tag ghcr.io/axmouth/axmouth.dev-user-client-builder --cache-from=ghcr.io/axmouth/axmouth.dev-user-client-builder
      - name: Build the new version of the final image
        run: docker build . --file Dockerfile.user.client.final --tag ghcr.io/axmouth/axmouth.dev-user-client --cache-from=ghcr.io/axmouth/axmouth.dev-user-client
      - name: Tag builder image
        run: docker tag ghcr.io/axmouth/axmouth.dev-user-client-builder latest
      - name: Tag final image
        run: docker tag ghcr.io/axmouth/axmouth.dev-user-client latest
      - name: Push builder image to GHCR
        run: docker push ghcr.io/axmouth/axmouth.dev-user-client-builder || true
      - name: Push final image to GHCR
        run: docker push ghcr.io/axmouth/axmouth.dev-user-client || true
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create empty .env file
        run: touch .env
      - name: Use docker-compose to remotely stop containers
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: DOCKER_HOST="ssh://$SERVER_USERNAME@$SERVER_IP:$SSH_PORT" docker-compose stop
      - name: Use docker-compose to remotely remove containers
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: DOCKER_HOST="ssh://$SERVER_USERNAME@$SERVER_IP:$SSH_PORT" docker-compose rm -f
      - name: Use docker-compose to remotely pull new containers
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: DOCKER_HOST="ssh://$SERVER_USERNAME@$SERVER_IP:$SSH_PORT" docker-compose pull
      - name: Use docker-compose to deploy remotely
        env:
          BIND_ADDRESS: 0.0.0.0:39051
          CAPTCHA_SECRET: ${{ secrets.CAPTCHA_SECRET }}
          CAPTCHA_VERIFY_URL: https://hcaptcha.com/siteverify
          CONTACT_ADDRESS: ${{ secrets.CONTACT_ADDRESS }}
          CONTAINER_NAME: axmouth.dev-postfix
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_DURATION: 500
          MAIL_FROM_ADDRESS: noreply@axmouth.dev
          MAIL_FROM_NAME: axmouth.dev
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          RUST_LOG: backend_api=error
          STATIC_FILE_DIR: /var/lib/axmouth/axmouth.dev/static-assets
          STATIC_FILE_ADDRESS: https://backend.axmouth.dev/static
          WEBSITE_URL: axmouth.dev
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: DOCKER_HOST="ssh://$SERVER_USERNAME@$SERVER_IP:$SSH_PORT" docker-compose up --remove-orphans -d
