name: Publish Docker image of axmouth.dev Backend to GHCR then update the image version on server

on: [push]

jobs:
  push_to_registry_and_deploy_to_server:
    if: github.ref == 'refs/heads/master'
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Github Container Registry with Docker
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      #- name: Pull the previous version of Docker image from Github Container Registry
      #  run: docker pull ghcr.io/axmouth/axmouth.dev-backend || true
      - name: Cache Docker build, to keep builder image
        id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp/docker-save
          key: docker-save-${{ hashFiles('Dockerfile') }}--
      - name: Load cached Docker artifactss
        run: docker load -i /tmp/docker-save/snapshot.tar || true
        if: steps.cache-docker.outputs.cache-hit == 'true'
      - name: Build the new version with latest tag
        run: docker build . -t latest --cache-from=backend-build-cache
      - name: Tag Container, Cache and Push the new version with latest tag
        run: docker tag latest backend-build-cache
      - name: Push to GHCR
        run: docker push ghcr.io/axmouth/axmouth.dev-backend || true
      - name: Create Directory to save Docker artifacts, if not exist
        run: mkdir -p /tmp/docker-save
      - name: Save Docker artifacts to an archive
        run: docker save backend-build-cache -o /tmp/docker-save/snapshot.tar
      - run: ls -lh /tmp/docker-save || true
      - name: Create .ssh folder if missing
        run: mkdir -p ~/.ssh
      - name: Add ssh key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: echo $SSH_KEY > ~/.ssh/id_rsa
      - name: Create empty .env file
        run: touch .env
      - name: Use docker-compose to deploy remotely
        env:
          BIND_ADDRESS: 0.0.0.0:39051
          CAPTCHA_SECRET: ${{ secrets.CAPTCHA_SECRET }}
          CAPTCHA_VERIFY_URL: https://hcaptcha.com/siteverify
          CONTACT_ADDRESS: ${{ secrets.CONTACT_ADDRESS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_DURATION: 500
          MAIL_FROM_ADDRESS: noreply@axmouth.dev
          MAIL_FROM_NAME: axmouth.dev
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          RUST_LOG: backend_api=error
          STATIC_FILE_DIR: /var/lib/axmouth/axmouth.dev/static-assets
          STATIC_FILE_ADDRESS: https://axmouth.dev/static
          WEBSITE_URL: axmouth.dev
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: DOCKER_HOST="ssh://$SERVER_USERNAME@$SERVER_IP" docker-compose up --remove-orphans -d
      - name: Remove ssh key. In case
        run: rm ~/ssh/id_rsa
