name: Deploy axmouth.dev Admin Frontend CD

on: [push]

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        working-directory: ./ng-client-user
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli > /dev/null
      - name: Build Project
        working-directory: ./ng-client-user
        run: npm run build:ci
        env:
          CI: true
      - name: Copy File via SSH Hey
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          source: "./ng-client-user/dist/ng-user-client/"
          target: "/var/lib/axmouth/axmouth.dev/ng-client-user/"
          strip_components: 3 # this is important
